# see compatibility table: https://github.com/docker/compose/releases
# see networking info: https://docs.docker.com/compose/networking/
version: '3'
services:
  mongo:
    build:
      context: ./mongo
      #user: root
      #volumes: - mongodata:/data/db
    ports:        
        - "2222:27017"  
    networks: 
      - backend        
  api:
    build:
      context: ./innovation-api  
      #user: root
    ports:
        - "8080:8080"  
    links:
      - mongo        
    #container_name: nesspoll-users   
    depends_on:
      - mongo 
    networks: 
      - backend      
  board:
    build:
      context: ./innovation-board
    #privileged: true
    #user: root
    ports:
      - "3000:3000"      
  
networks:
    backend:
        driver: "bridge"  
